# Cloudflare Pages configuration
name = "neuropul-ai"
compatibility_date = "2024-06-29"

[build]
  command = "npm run build"
  publish = "dist"

[env]
  NODE_VERSION = "20"

[build.environment]
  VITE_SUPABASE_URL = "https://blmvkduhlkbovgrabthx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbXZrZHVobGtib3ZncmFidGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTE3NjUsImV4cCI6MjA2NjA4Nzc2NX0.6AYOciFxfGqEerXPhWfGfQ6sTyWzHKnggX-r0iKbHoM"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbXZrZHVobGtib3ZncmFidGh4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDUxMTc2NSwiZXhwIjoyMDY2MDg3NzY1fQ.DLTMgIzG_36-SWFQpSLETjnH--Q9RnqsY5EPtd1BHMY"
  OPENAI_API_KEY = "sk-proj-HtKilSKj2bdLO5wcuIEMKST1tcq"
  APP_ENV = "production"
  ENABLE_DEBUG = "true"
  DISABLE_PDF_GEN = "false"
  DEFAULT_LANGUAGE = "ru"
  TIMEOUT = "30000"
  CHECK_STATUS = "true"
  ERROR_LOGGER = "true"

[site]
  bucket = "./dist"
  entry-point = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://api.dicebear.com https://*.supabase.co https://*.pexels.com; connect-src 'self' https://*.supabase.co https://api.openai.com;"