[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["html2canvas", "jspdf", "qrcode"]

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  VITE_SUPABASE_URL = "https://blmvkduhlkbovgrabthx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbXZrZHVobGtib3ZncmFidGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTE3NjUsImV4cCI6MjA2NjA4Nzc2NX0.6AYOciFxfGqEerXPhWfGfQ6sTyWzHKnggX-r0iKbHoM"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbXZrZHVobGtib3ZncmFidGh4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDUxMTc2NSwiZXhwIjoyMDY2MDg3NzY1fQ.DLTMgIzG_36-SWFQpSLETjnH--Q9RnqsY5EPtd1BHMY"
  OPENAI_API_KEY = "sk-proj-HtKilSKj2bdLO5wcuIEMKST1tcq"
  APP_ENV = "production"
  ENABLE_DEBUG = "true"
  DISABLE_PDF_GEN = "false"
  DEFAULT_LANGUAGE = "ru"
  TIMEOUT = "30000"
  CHECK_STATUS = "true"
  ERROR_LOGGER = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://api.dicebear.com https://*.supabase.co https://*.pexels.com https://media.giphy.com https://neuropul.uz; connect-src 'self' https://*.supabase.co https://api.openai.com;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true