[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["html2canvas", "jspdf", "qrcode"]

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  VITE_SUPABASE_URL = "https://blmvkduhlkbovgrabthx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbXZrZHVobGtib3ZncmFidGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTE3NjUsImV4cCI6MjA2NjA4Nzc2NX0.6AYOciFxfGqEerXPhWfGfQ6sTyWzHKnggX-r0iKbHoM"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbXZrZHVobGtib3ZncmFidGh4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDUxMTc2NSwiZXhwIjoyMDY2MDg3NzY1fQ.DLTMgIzG_36-SWFQpSLETjnH--Q9RnqsY5EPtd1BHMY"
  OPENAI_API_KEY = "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"
  APP_ENV = "dev"
  ENABLE_DEBUG = "true"
  DISABLE_PDF_GEN = "false"
  DEFAULT_LANGUAGE = "ru"
  TIMEOUT = "30000"
  CHECK_STATUS = "true"
  ERROR_LOGGER = "true"